marks = []

f1 = int(input("Enter 1st students marks : "))
marks.append(f1)
f2 = int(input("Enter 2nd students marks : "))
marks.append(f2)
f3 = int(input("Enter 3rd students marks : "))
marks.append(f3)
f4 = int(input("Enter 4th students marks : "))
marks.append(f4)
f5 =int( input("Enter 5th students marks : "))
marks.append(f5)
f6 = int(input("Enter 6th students marks : "))
marks.append(f6)
f7 = int(input("Enter 7th students marks : "))
marks.append(f7)
marks.sort()
print(marks)